files = """
main
"""
objects = [("%s.o" % f) for f in files.split()]

Import('env')

for f in files.split():
    env.Object("%s.cpp" %f)

env.Append(LIBS = ["boost_serialization"])
env.reader = env.Program('cfg', objects)
