files = """
pvfregs
"""
objects = [("%s.o" % f) for f in files.split()]

Import('env')

for f in files.split():
    env.Object("%s.cpp" %f)

env.pvf = env.Program('pvfregs', objects)
env.Append(LIBS = ["boost_serialization"])
