files = """
test
wvtest
wvtestmain
"""

objects = [("%s.o" % f) for f in files.split()]

Import('env')
env.Append(CPPDEFINES = ["WVTEST_CONFIGURED"])

for f in files.split():
    env.Object("%s.cpp" %f)

env.test = env.Program('cfgtest', objects)
