files = """
reader
"""
objects = [("%s.o" % f) for f in files.split()]

Import('env')

for f in files.split():
    env.Object("%s.cpp" %f)

env.reader = env.Program('reader', objects)
env.Append(LIBS = ["boost_serialization"])
