--- !ditz.rubyforge.org,2008-03-06/project 
name: CFGAnalysis
version: "0.5"
components: 
- !ditz.rubyforge.org,2008-03-06/component 
  name: CFGAnalysis
releases: 
- !ditz.rubyforge.org,2008-03-06/release 
  name: "0.1"
  status: :released
  release_time: 2012-08-14 11:53:08.449438 Z
  log_events: 
  - - 2012-08-13 09:55:54.704006 Z
    - doebel <doebel@tudos.org>
    - created
    - ""
  - - 2012-08-14 11:53:08.449460 Z
    - doebel <doebel@tudos.org>
    - released
    - ""
- !ditz.rubyforge.org,2008-03-06/release 
  name: "0.2"
  status: :released
  release_time: 2012-08-22 20:54:29.009757 Z
  log_events: 
  - - 2012-08-13 09:58:09.299057 Z
    - doebel <doebel@tudos.org>
    - created
    - ""
  - - 2012-08-22 20:54:29.009778 Z
    - doebel <doebel@tudos.org>
    - released
    - "!"
- !ditz.rubyforge.org,2008-03-06/release 
  name: "0.3"
  status: :unreleased
  release_time: 
  log_events: 
  - - 2012-08-14 11:57:21.773501 Z
    - doebel <doebel@tudos.org>
    - created
    - ""
- !ditz.rubyforge.org,2008-03-06/release 
  name: "0.4"
  status: :unreleased
  release_time: 
  log_events: 
  - - 2012-08-20 15:47:35.511753 Z
    - doebel <doebel@tudos.org>
    - created
    - ""
- !ditz.rubyforge.org,2008-03-06/release 
  name: "0.5"
  status: :unreleased
  release_time: 
  log_events: 
  - - 2012-09-12 05:49:42.696234 Z
    - doebel <doebel@tudos.org>
    - created
    - ""
