files = """
cfg
cfgbuilder
cfg_search
disassembler
input
udis86_helper
util
"""

Import('env')

obj = []

for f in files.split():
    obj += [env.Object("%s.cpp" %f)]

env.analyzerlib = env.Library('analyzer', obj)
