files = """
cfg
cfgbuilder
disassembler
input
instructionProps_udis86
udis86_helper
util
"""

Import('env')

obj = []

for f in files.split():
    obj += [env.Object("%s.cpp" %f)]

env.analyzerlib = env.Library('analyzer', obj)
