files = """
dynrun
syscallnames
"""

objects = [("%s.o" % f) for f in files.split()]

Import('env')
for f in files.split():
    env.Object('%s.cpp' % f)

env.Append(LIBS=['boost_serialization'])
env.dynrun = env.Program('dynrun', objects)
