#!/bin/bash

ditz html issues/html
cp issues/myIssueStyles.css issues/html/style.css
rsync  -r issues/html/ doebel@os.inf.tu-dresden.de:public_html/cfg/issues/
git add issues
git commit -m "issue update"
git push
