#!/bin/bash

ditz html issues/html
ssh doebel@os.inf.tu-dresden.de rm -rf public_html/cfg/issues
scp -r issues/html doebel@os.inf.tu-dresden.de:public_html/cfg/issues
git add issues
git commit -m "issue update"
git push
